import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatSapButton";
import { ClerkProvider } from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hanvil Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Full-width background with centered content */}
        {/* <header className="w-full bg-blue-500">
          <div className="max-w-7xl mx-auto">
          </div>
        </header> */}
            <Navbar />
        
        {/* Main content container */}
        <main className="max-w-7xl mx-auto p-4">
          {children}
        </main>
        <WhatsAppButton/>
       <Footer/>
          
      </body>
    </html>
     </ClerkProvider>
  );
}